"""add submissions

Revision ID: 9d86901f70d9
Revises: a51c69aa151f
Create Date: 2026-02-02 13:18:20.969712

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "9d86901f70d9"
down_revision: Union[str, Sequence[str], None] = "a51c69aa151f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
