"""add max_score to assignments

Revision ID: a0f5e6614d92
Revises: 9d86901f70d9
Create Date: 2026-02-09 16:31:03.790221

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a0f5e6614d92"
down_revision: Union[str, Sequence[str], None] = "9d86901f70d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignments",
        sa.Column("max_score", sa.Float(), server_default="100", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assignments", "max_score")
    # ### end Alembic commands ###
