"""add enrollments

Revision ID: c607b00de799
Revises:
Create Date: 2026-02-02 11:58:46.005148

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c607b00de799"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
